language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: gYzpqe9R38/gnTnB3tl0dcK7njWFvGUNW7408M3HQ2m1Sym7kRmkHJLBnKqZyhddJz5PqwRL2mSDusoRYlD/liqURvdwkr20zMAjMKsF44h6dakFO8cdwEl80b0OB8sjwKm8rfU2SNGJnaVExHPGxwtLzr4QgRkqEvr52wiErMGl+PSKa2JI6Wn6GL4dCdqUcca75RE4OE9x6yMTQOfKxW9sgrrK4zS3Ld9v1lZ65rpCBxpDc+vlC7vgpScN5uhRl6JNI2LeOU4Iox4lHPYgLZTBdBhoj3D1jzyslbzjN2wvca8lmH+0OKh2IOC5wG6+dpJWkffNm/FtOChVuLGHWAqbDMJ//SSGTI7MPbmT7yfxIRVb9llwmDtbowuqCDZAPFDPSUno8iJ0et41hCLHmzX0S10kpdl+avnzcP5ctAZR5MdqV1LVyh2JM+clLPz6d/jYA/T8xVRQdyIYbSIPe1Ed1Ld8QEAuKnSTd7wpRjxMTIy1tRhNpw92DcDVXap4ywoYKS4am2Wm10F03v8VbmczK4dqyf63oAqZF+xMoPb6ykBcK5DAbY1sTFvR4gS3TUZcJSeoBQWPlvmFGP8cqoDF+ePpUWuwjRPWZCngNGstGF/OXotgKSFNYH8uUjZV5NB0zDcfBMNm1ieCyDt0p1FVD7iS8SubFRKgP0ri+xg=
  app: shrouded-inlet-26742